export enum AUTH_ERRORS {
  EMAIL_OR_PASSWORD_IS_INCORRECT = "EMAIL_OR_PASSWORD_IS_INCORRECT",
  TOKEN_FORMAT_IS_INCORRECT = "TOKEN_FORMAT_IS_INCORRECT",
  TOKEN_IS_INVALID = "TOKEN_IS_INVALID",
  TOKEN_IS_EXPIRED = "TOKEN_IS_EXPIRED",
  TOKEN_NOT_INFORMED = "TOKEN_NOT_INFORMED",
  REFRESH_TOKEN_IS_INVALID = "REFRESH_TOKEN_IS_INVALID",
  REFRESH_TOKEN_IS_EXPIRED = "REFRESH_TOKEN_IS_EXPIRED"
}