export enum USER_ERRORS {
  NOT_FOUND = "USER_NOT_FOUND"
}

export enum CREATE_USER_ERRORS {
  PASSWORD_CONFIRMATION_DOES_NOT_MATCH = "PASSWORD_CONFIRMATION_DOES_NOT_MATCH",
  ALREADY_EXISTS = "USER_ALREADY_EXISTS"
}